position = "Top"
clipboard_cmd = "cliphist-rofi-img | wl-copy"
app_launcher_cmd = "walker"

[appearance]
font_name = "JetBrainsMono Nerd Font"
opacity = 0.8
backdrop = 0.5
primary_color = "#7eceff"
success_color = "#eceff4"
text_color = "#eceff4"
scale = 1.5 
workspace_colors = [ "#7aa2f7", "#9ece6a" ]
style="Islands"

[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"

[appearance.background_color]
base = "#2e3440"
weak = "#4c566a"
strong = "#8e51ac"

[appearance.secondary_color]
base = "#3b4252"

[modules]
left = [ ["appLauncher", "Browse", "Gemini", "Spotify", "Vscode", "Anytype", "Pacmac"], [ "Tray" ] ]
center = [ [ "Workspaces" ], [ "MediaPlayer" ] ]
right = [ "SystemInfo", [ "Clock", "Privacy", "Settings" ], "CustomNotifications" ] 

[workspaces]
visibility_mode = "All"
max_workspaces = 6
enable_workspace_filling = true

[updates]
check_cmd = "checkupdates; paru -Qua"
update_cmd = 'kitty -e bash -c "paru; echo Done - Press enter to exit; read" &'

[clock]
format = "%H:%M  %d-%m-%Y"

[media_player]
max_title_length = 50

[settings]
lock_cmd = "playerctl --all-players pause; hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_source_more_cmd = "pavucontrol -t 4"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueman-manager"
remove_airplane_btn = true

[[CustomModule]]
name = "appLauncher"
icon = "󱗼"
command = "walker -w 700 -h 1024"

[system]
indicators = [ "DownloadSpeed", "UploadSpeed", "Temperature", "Cpu", "Memory" ]

[[CustomModule]]
name = "CustomNotifications"
icon = ""
command = "swaync-client -t"
listen_cmd = "swaync-client -swb"
icons.'dnd.*' = ""
alert = ".*notification"

[[CustomModule]]
name = "Browse"
icon = ""
command = "google-chrome-stable"

[[CustomModule]]
name = "Gemini"
icon = ""
command = "google-chrome-stable --app='https://gemini.google.com'"

[[CustomModule]]
name = "Spotify"
icon = "󰓇"
command = "spotify-launcher"

[[CustomModule]]
name = "Vscode"
icon = ""
command = "code"

[[CustomModule]]
name = "Anytype"
icon = "󰛜"
command = "anytype"

[[CustomModule]]
name = "Pacmac"
icon = ""
command = "pamac-manager"
