position = "Top"
clipboard_cmd = "cliphist-rofi-img | wl-copy"
app_launcher_cmd = "walker"

[appearance]
font_name = "JetBrainsMono Nerd Font"
opacity = 0.7
backdrop = 0.3
primary_color = "#7aa2f7"
success_color = "#9ece6a"
text_color = "#a9b1d6"

workspace_colors = [ "#7aa2f7", "#9ece6a" ]

[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"

[appearance.background_color]
base = "#1a1b26"
weak = "#24273a"
strong = "#414868"

[appearance.secondary_color]
base = "#0c0d14"

[modules]
left = [ ["appLauncher", "Browse", "Spotify", "Vscode", "Pacmac"], [ "Tray" ] ]
center = [ [ "Workspaces" ], [ "MediaPlayer" ] ]
right = [ "SystemInfo", [ "Clock", "Privacy", "Settings", "CustomNotifications"  ] ]

[workspaces]
visibility_mode = "All"
max_workspaces = 6
enable_workspace_filling = true

[clock]
format = "%H:%M  %d-%m-%Y"

[media_player]
max_title_length = 50

[settings]
lock_cmd = "playerctl --all-players pause; hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_source_more_cmd = "pavucontrol -t 4"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueman-manager"
remove_airplane_btn = true

[[CustomModule]]
name = "appLauncher"
icon = "󱗼"
command = "walker -w 700 -h 1024"

[system]
indicators = [ "DownloadSpeed", "UploadSpeed", "Temperature", "Cpu", "Memory" ]

[[CustomModule]]
name = "CustomNotifications"
icon = ""
command = "swaync-client -t -sw"
listen_cmd = "swaync-client -swb"
icons.'dnd.*' = ""
alert = ".*notification"

[[CustomModule]]
name = "Browse"
icon = ""
command = "google-chrome-stable"

[[CustomModule]]
name = "Spotify"
icon = "󰓇"
command = "spotify-launcher"

[[CustomModule]]
name = "Vscode"
icon = ""
command = "code"

[[CustomModule]]
name = "Pacmac"
icon = ""
command = "pamac-manager"
